### ISSUE TITLE
I changed cfg file for not have enough memory,and got training wrong.

### ISSUE THREAD

**Issue by ltc576935585** [ppengtang/pcl.pytorch#16]
I changed the cfg file as:
MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: vgg16.dilated_conv5_body
NUM_GPUS: 1
VGG:
  IMAGENET_PRETRAINED_WEIGHTS: 'data/pretrained_model/vgg16_caffe.pth'
SOLVER:
  WEIGHT_DECAY: 0.0005
  LR_POLICY: steps_with_decay
  BASE_LR: 0.001
  GAMMA: 0.1
  # 1x schedule (note TRAIN.IMS_PER_BATCH: 1)
  MAX_ITER: 10000 #50000
  STEPS: [0, 35000]
FAST_RCNN:
  ROI_BOX_HEAD: vgg16.roi_2mlp_head
  ROI_XFORM_METHOD: RoIPoolF
  ROI_XFORM_RESOLUTION: 7
  MLP_HEAD_DIM: 4096
TRAIN:
  SCALES:  (480, 576) #(480, 576, 688, 864, 1200)
  MAX_SIZE: 1000 #2000
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 4096 #4096
  PROPOSAL_FILES: ('data/selective_search_data/voc_2007_trainval.pkl',)
TEST:
  SCALE: 240 #480
  MAX_SIZE: 1000 #2000
  NMS: 0.3
  PROPOSAL_FILES: ('data/selective_search_data',)
  BBOX_AUG:
    ENABLED: True
    H_FLIP: True
    SCALES: (576, 688) #(576, 688, 864, 1200)
    SCALE_H_FLIP: True
    SCORE_HEUR: 'AVG'
    COORD_HEUR: 'ID'

when I training,I got this:
[Aug03-19-45-42_ltcpc_step][vgg16_voc2007.yaml][Step 10000 / 10000]
                loss: 0.033960, lr: 0.001000 time: 0.545583, eta: 0:00:00
                loss_im_cls: 0.003680, refine_loss0: 0.001562, refine_loss1: 0.004210, refine_loss2: 0.009765
INFO train_net_step.py: 135: save model: Outputs/vgg16_voc2007/Aug03-19-45-42_ltcpc_step/ckpt/model_step9999.pth
INFO train_net_step.py: 135: save model: Outputs/vgg16_voc2007/Aug03-19-45-42_ltcpc_step/ckpt/model_step9999.pth
Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7f336f6fbe10>>
Traceback (most recent call last):
  File "/home/ltc/anaconda3/envs/MELM/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 399, in __del__
    self._shutdown_workers()
  File "/home/ltc/anaconda3/envs/MELM/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 378, in _shutdown_workers
    self.worker_result_queue.get()
  File "/home/ltc/anaconda3/envs/MELM/lib/python3.6/multiprocessing/queues.py", line 337, in get
    return _ForkingPickler.loads(res)
  File "/home/ltc/anaconda3/envs/MELM/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 151, in rebuild_storage_fd
    fd = df.detach()
  File "/home/ltc/anaconda3/envs/MELM/lib/python3.6/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/home/ltc/anaconda3/envs/MELM/lib/python3.6/multiprocessing/reduction.py", line 182, in recv_handle
    return recvfds(s, 1)[0]
  File "/home/ltc/anaconda3/envs/MELM/lib/python3.6/multiprocessing/reduction.py", line 155, in recvfds
    raise EOFError
EOFError:

**Comment by ppengtang** [comment]
Hi, this doesn't matter. Because you set "MAX_ITER" to 10000 and you have already saved the final model ("model_step9999.pth").
