### ISSUE TITLE
The missing file"pcl.pytorch/data/VOC2007/annotations/voc_2007_trainval.json"

### ISSUE THREAD

**Issue by zwy1996** [ppengtang/pcl.pytorch#25]
Hello, Thanks for your excellent work. When i used the code , i met the following error. Could you help me deal with it? Thanks very much!
Traceback (most recent call last):
  File "tools/train_net_step.py", line 443, in <module>
    main()
  File "tools/train_net_step.py", line 227, in main
    cfg.TRAIN.DATASETS, cfg.TRAIN.PROPOSAL_FILES)
  File "/data1/zwy/pcl.pytorch/lib/datasets/roidb.py", line 59, in combined_roidb_for_training
    roidbs = [get_roidb(*args) for args in zip(dataset_names, proposal_files)]
  File "/data1/zwy/pcl.pytorch/lib/datasets/roidb.py", line 59, in <listcomp>
    roidbs = [get_roidb(*args) for args in zip(dataset_names, proposal_files)]
  File "/data1/zwy/pcl.pytorch/lib/datasets/roidb.py", line 40, in get_roidb
    ds = JsonDataset(dataset_name)
  File "/data1/zwy/pcl.pytorch/lib/datasets/json_dataset.py", line 62, in __init__
    'Annotation file \'{}\' not found'.format(DATASETS[name][ANN_FN])
AssertionError: Annotation file '/data1/zwy/pcl.pytorch/data/VOC2007/annotations/voc_2007_trainval.json' not found

**Comment by ppengtang** [comment]
Hi, please follow [Installation for training and testing](https://github.com/ppengtang/pcl.pytorch#installation-for-training-and-testing) in README before training and testing your models.

**Comment by zwy1996** [comment]
Thank you very much, I get it now.
