### ISSUE TITLE
Generating VOC2012  test result problem

### ISSUE THREAD

**Issue by HqWei** [ppengtang/pcl.pytorch#37]
When I test my trained model on VOC2012, i get the following err:

Traceback (most recent call last):
  File "tools/test_net.py", line 134, in <module>
    check_expected_results=True)
  File "voc2012/no-trick/baseline_iter5/oicr_project/lib/core/test_engine.py", line 127, in run_inference
    all_results = result_getter()
  File "voc2012/no-trick/baseline_iter5/oicr_project/lib/core/test_engine.py", line 107, in result_getter
    multi_gpu=multi_gpu_testing
  File "voc2012/no-trick/baseline_iter5/oicr_project/lib/core/test_engine.py", line 157, in test_net_on_dataset
    args, dataset_name, proposal_file, output_dir, gpu_id=gpu_id
  File "voc2012/no-trick/baseline_iter5/oicr_project/lib/core/test_engine.py", line 236, in test_net
    dataset_name, proposal_file, ind_range
  File "voc2012/no-trick/baseline_iter5/oicr_project/lib/core/test_engine.py", line 336, in get_roidb_and_dataset
    proposal_limit=cfg.TEST.PROPOSAL_LIMIT
  File "voc2012/no-trick/baseline_iter5/oicr_project/lib/datasets/json_dataset.py", line 155, in get_roidb
    crowd_filter_thresh
  File "voc2012/no-trick/baseline_iter5/oicr_project/lib/datasets/json_dataset.py", line 231, in _add_proposals_from_file
    assert entry['id'] == proposals[id_field][i]
AssertionError
srun: error: SH-IDC2-172-20-20-69: task 0: Exited with exit code 1
srun: Terminating job step 678835.0

**Comment by HqWei** [comment]
I got it ! int(entry['id'])
