### ISSUE TITLE
Error training voc2007

### ISSUE THREAD

**Issue by ch13d2am** [ppengtang/pcl.pytorch#83]
Hi

I'm a student and a complete newbie, so please forgive me if this is a basic question. I have followed the instructions to run PCL on the voc2007 data.

I'm using Windows 10, Python 3.10.5, and as far as I can tell I've installed all dependencies including Visual Studio Code C++ libraries, SDK etc., although I had a lot of trouble trying to install cython_bbox.

When I run "python tools/test_net.py --cfg configs/baselines/vgg16_voc2007.yaml \ --load_ckpt Outputs/vgg16_voc2007/$MODEL_PATH \ --dataset voc2007trainval" I get the following:

C:\Users\####\py_virtual_env\lib\site-packages\torchvision\models\detection\anchor_utils.py:63: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xf (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:68.)
  device: torch.device = torch.device("cpu"),
Traceback (most recent call last):
  File "C:\Users\####\pcl.pytorch\tools\test_net.py", line 14, in <module>
    from core.test_engine import run_inference
  File "C:\Users\####\pcl.pytorch\lib\core\test_engine.py", line 36, in <module>
    from core.test import im_detect_all
  File "C:\Users\####\pcl.pytorch\lib\core\test.py", line 43, in <module>
    import utils.boxes as box_utils
  File "C:\Users\####\pcl.pytorch\lib\utils\boxes.py", line 54, in <module>
    import utils.cython_bbox as cython_bbox
ModuleNotFoundError: No module named 'utils.cython_bbox'

I also have: Requirement already satisfied: cython_bbox in c:\users\####\py_virtual_env\lib\site-packages (0.1.3)
I've searched for a solution on stackoverflow etc. but cannot find one.
I'd appreciate any help.

**Comment by ShirleySyh** [comment]
Hi, have you soloved this problem yet? I met the same problem when trying to use the PCL in my own code.

**Comment by ch13d2am** [comment]
Hi

I ended up using Google Colab instead of my own installation of Python. Make sure you set up Colab in line with the requirements text file for PCL, and it should work.

Good luck.
